// components/pages/Contact.vue
<template>
    <div class="desc" id="contact">
        <div style="width:411px;float: left;">
        <p>Mag. (FH) Mario Rothauer<br />
            Am Birkenweg 3<br />
            A-4644 Scharnstein / <span class="lang en">Austria</span><span class="lang de">Österreich</span>
        </p>
        <p>
            <b>Büro-Adresse:</b><br />
            Grubbachstraße 14<br />
            A-4644 Scharnstein
        </p>
        <p>+43 680 217 89 39<br />
            [email]<br />
            UID-Nr. ATU71726279<br />
        </p>
        <p>
            <b>Geschäftszeiten:</b><br />
            Montag bis Mittwoch 08:30 bis 17:30 Uhr, Donnerstag 08:30 bis 12:00
        </p>
        <p>
            <a target="_blank" class="img" title="xing" href="https://www.xing.com/profile/Mario_Rothauer">
            <img src="/img/xing_icon_16x16.png" />
            </a>
            <a target="_blank" class="img" title="linkedin" href="https://at.linkedin.com/in/mrothauer">
            <img src="/img/linkedin_icon_16x16.png" />
            </a>
        </p>
        </div>
        <div style="width:250px;float:left;">
        <a target="_blank" style="float:right;" title="Klimabündnis" href="https://www.klimabuendnis.at/betriebe-mitglieder/rothauerwebsites">
            <img style="float:right;" width="250" src="/img/klimabuendnislogo.jpg" />
        </a>
        </div>
    </div>
</template>

// src/app/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-contact',
    templateUrl: './contact.component.html',
})
export class ContactComponent implements OnInit {

    constructor() { }

    ngOnInit() {

    }

}
<div class="desc" id="contact" style="display: none;">
    <div style="width:411px;float: left;">
        <p>Mag. (FH) Mario Rothauer</p>
        <p>Am Birkenweg 3</p>
        <p>A-4644 Scharnstein / <span class="lang en" style="display: none;">Austria</span><span class="lang de"
                style="display: inline;">Österreich</span></p>
        <p>+43 680 217 89 39</p>
        <p><a href="mailto:office@rothauer-it.com">office@rothauer-it.com</a></p>
        <p>UID-Nr. ATU71726279</p>
        <p>
            <a target="_blank" class="img" title="xing" href="https://www.xing.com/profile/Mario_Rothauer">
                <img src="/assets/img/xing_icon_16x16.png">
            </a>
            <a target="_blank" class="img" title="linkedin" href="https://at.linkedin.com/in/mrothauer">
                <img src="/assets/img/linkedin_icon_16x16.png">
            </a>
        </p>
    </div>
    <div style="width:250px;float:left;">
        <a target="_blank" style="float:right;" title="Klimabündnis"
            href="https://www.klimabuendnis.at/betriebe-mitglieder/rothauerwebsites">
            <img style="float:right;" width="250" src="/assets/img/klimabuendnislogo.jpg">
        </a>
    </div>
    <a class="header-link" href="#wrapper"><span class="lang en" style="display: none;">&lt;&lt;
            back</span><span class="lang de" style="display: inline;">&lt;&lt; zurück</span></a>
</div>
