// src/app/squares/squares.component.ts
import { Component, OnInit } from '@angular/core';
import { Square } from '../square/square';

@Component({
  selector: 'app-squares',
  templateUrl: './squares.component.html',
  styleUrls: ['./squares.component.css']
})
export class SquaresComponent implements OnInit {

  public squares: Square[] = [];

  constructor() {
    this.setSquares();
  }

  ngOnInit() {
  }

  setSquares() {
    this.squares.push(new Square('div', ['first-column', 'first-row']));
    this.squares.push(new Square('div', ['first-row']));
    this.squares.push(new Square('div', ['first-row']));
    this.squares.push(new Square('div', ['first-row']));
    this.squares.push(new Square('div', ['first-row']));
    this.squares.push(new Square('div', ['first-row']));
    this.squares.push(new Square('div', ['last-column', 'first-row']));

    this.squares.push(new Square('div', ['first-column']));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div', ['last-column']));

    this.squares.push(new Square('div', ['first-column']));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('a', ['notEmpty', 'hasImage'], '_blank',
      `<div class="heading heading-with-break">
      open source<br>github
      </div>
      <img src="/assets/thumbs/small/github.png" style="display: none;">`
    ));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('a', ['notEmpty', 'hasImage'], '_blank',
      `<div class="heading heading-with-break">
      foodcoop<br>shop.com
      </div>
      <img src="/assets/thumbs/small/foodcoopshop.png" style="display: none;">`
    ));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div', ['last-column']));

    this.squares.push(new Square('div', ['first-column']));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div'));
    this.squares.push(new Square('div', ['last-column']));

    this.squares.push(new Square('div', ['first-column', 'last-row']));
    this.squares.push(new Square('a', ['last-row', 'projects', 'notEmpty', 'hasNoImage'], null,
      `<div class="heading" style="margin-top: 22px;">
      <span class="lang de" style="display: inline;">projekte</span>
    </div>`
    ));
    this.squares.push(new Square('a', ['last-row', 'contact', 'notEmpty', 'hasNoImage'], null,
      `<div class="heading" style="margin-top: 22px;">
      <span class="lang de" style="display: inline;">kontakt</span>
    </div>`
    ));
    this.squares.push(new Square('a', ['last-row', 'about', 'notEmpty', 'hasNoImage'], null,
      `<div class="heading" style="margin-top: 22px;">
      <span class="lang de" style="display: inline;">über mich</span>
    </div>`
    ));
    this.squares.push(new Square('a', ['last-row', 'imprint', 'notEmpty', 'hasNoImage'], null,
      `<div class="heading" style="margin-top: 22px;">
      <span class="lang de" style="display: inline;">impressum</span>
    </div>`
    ));
    this.squares.push(new Square('a', ['last-row', 'privacy', 'notEmpty', 'hasNoImage'], null,
      `<div class="heading" style="margin-top: 22px;">
      <span class="lang de" style="display: inline;">datenschutz</span>
    </div>`
    ));
    this.squares.push(new Square('div', ['last-column', 'last-row']));

  }

}

<div class="squares">

    <div *ngFor="let square of squares, index as i">
        <app-square [square]="square" [index]="i"></app-square>
    </div>

    <div id="desc" class="description square" style="display:block;">
        <app-desc></app-desc>
        <app-about></app-about>
        <app-contact></app-contact>
        <app-imprint></app-imprint>
        <app-privacy></app-privacy>
    </div>

</div>

// components/Squares.vue
<style src="./Squares.css"></style>

<template>
    <div class="square first-column first-row" id="square-0"></div>
    <div class="square first-row" id="square-1"></div>
    <div class="square first-row" id="square-2"></div>
    <div class="square first-row" id="square-3"></div>
    <div class="square first-row" id="square-4"></div>
    <div class="square first-row" id="square-5"></div>
    <div class="square last-column first-row" id="square-6"></div>
    <div class="square first-column" id="square-7"></div>
    <div class="square" id="square-8"></div>
    <div class="square" id="square-9"></div>
    <div class="square" id="square-10"></div>
    <div class="square" id="square-11"></div>
    <div class="square" id="square-12"></div>
    <div class="square last-column" id="square-13"></div>
    <div class="square first-column" id="square-14"></div>
    <div class="square" id="square-15"></div><a href="https://dorfladen-online.at" class="square notEmpty hasImage"
        id="square-16" target="_blank">
        <div class="heading heading-with-break">dorfladen-<br>online.at</div><img
            src="/thumbs/small/dorfladen-online.png" style="display: none;">
    </a><a href="https://www.foodcoopshop.com" class="square notEmpty hasImage" id="square-17" target="_blank">
        <div class="heading heading-with-break">foodcoop<br>shop.com</div><img src="/thumbs/small/foodcoopshop.png"
            style="display: none;">
    </a><a href="https://www.hofladen-online.at" class="square notEmpty hasImage" id="square-18" target="_blank">
        <div class="heading heading-with-break">hofladen-<br>online.at</div><img
            src="/thumbs/small/hofladen-online.jpg" style="display: none;">
    </a>
    <div class="square" id="square-19"></div>
    <div class="square last-column" id="square-20"></div>
    <div class="square first-column" id="square-21"></div>
    <div class="square" id="square-22"></div>
    <div class="square" id="square-23"></div><a href="https://github.com/mrothauer" class="square notEmpty hasImage"
        id="square-24" target="_blank">
        <div class="heading heading-with-break">open source<br>github</div><img src="/thumbs/small/github.png"
            style="display: none;">
    </a>
    <div class="square" id="square-25"></div>
    <div class="square" id="square-26"></div>
    <div class="square last-column" id="square-27"></div>
    <div class="square first-column last-row" id="square-28"></div><a href="#desc"
        class="square last-row projects notEmpty hasNoImage" id="square-29">
        <div class="heading" style="margin-top: 22px;"><span class="lang de">projekte</span><span
                class="lang en">projects</span></div>
    </a><a href="#desc" class="square last-row contact notEmpty hasNoImage" id="square-30">
        <div class="heading" style="margin-top: 22px;"><span class="lang de">kontakt</span><span
                class="lang en">contact</span></div>
    </a><a href="#desc" class="square last-row about notEmpty hasNoImage selected" id="square-31">
        <div class="heading" style="margin-top: 22px;"><span class="lang de">über mich</span><span
                class="lang en">about</span></div>
    </a><a href="#desc" class="square last-row imprint notEmpty hasNoImage" id="square-32">
        <div class="heading" style="margin-top: 22px;"><span class="lang de">impressum</span><span
                class="lang en">imprint</span></div>
    </a><a href="#desc" class="square last-row privacy notEmpty hasNoImage" id="square-33">
        <div class="heading" style="margin-top: 22px;"><span class="lang de">datenschutz</span><span
                class="lang en">privacy</span></div>
    </a>
    <div class="square last-column last-row" id="square-34"></div>
</template>
