// src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-about',
    templateUrl: './about.component.html',
})
export class AboutComponent implements OnInit {

    constructor() { }

    ngOnInit() {

    }

}
<div class="desc" id="about" style="display: block;">

    <div>

        <img alt="Mario Rothauer" width="200" height="200" src="/assets/img/profilbild-netidee.jpg">

        <b>
            <span><a style="text-decoration: underline"
                    href="https://www.foodcoopshop.com/2019/01/foodcoopshop-im-extra-blick/" target="_blank"><span
                        style="float: none;">Bericht über FoodCoopShop im extra-blick
                        (31.01.2019)</span></a></span>
        </b>
        <br><br>

        <b>
            <a style="text-decoration: underline"
                href="https://www.foodcoopshop.com/2018/06/leitartikel-vom-markt-platz-zum-online-markt/"
                target="_blank">Leitartikel für "Leben in Stadt und Land" (2018)</a>
        </b>
        <br>
        <br>

        <b>
            <span class="lang de" style="display: inline;">Bericht über FoodCoopShop in der Tips
                (14.03.2018)</span>
            <span class="lang en" style="display: none;">Article about FoodCoopShop in Tips (in German)</span>
        </b><br>
        <p>
            <a style="text-decoration: underline"
                href="https://www.tips.at/news/scharnstein/wirtschaft-politik/419922-digitalisierung-unterstuetzt-die-nahversorgung-im-almtal"
                target="_blank"><span style="float: none; display: inline;" class="lang de">Online-Version</span><span
                    style="float: none; display: none;" class="lang en">online version</span></a>
            / <a style="text-decoration: underline" target="_blank"
                href="https://www.tips.at/zeitung-epaper/?ausgabe=tips-gmunden&amp;id=31669#/22"><span
                    style="float: none; display: inline;" class="lang de">Print-Ausgabe</span><span
                    style="float: none; display: none;" class="lang en">print version</span></a>
        </p>

        <br>

        <p class="lang en" style="display: none;">
            <b>About me</b>: After finising the University of Applied Science in Vienna and gaining lots of work
            experience in South Armerica and Berlin, Mario works as a freelance web programmer in the beautiful
            Almtal
            (Upper Austria) since 2009.
        </p>
        <p class="lang de" style="display: block;">
            <b>Über mich</b>: Nach dem FH-Studium für Projektmanagement und Informationstechnik in Wien und
            mehreren
            fachbezogenenen Auslandsaufenthalten in Südamerika und Berlin bietet Mario seit 2009 seine
            Programmier-Dienstleistungen zur Erstellung von webbasierter Software an.
        </p>
        <p class="lang de" style="display: block;">Am liebsten arbeitet er an Open-Source-Projekten, die zu
            einer
            Verbesserung der Gesellschaft beitragen. Mario lebt mit seiner Familie im Almtal.
        </p>

        <br>
        <p>
            <b>
                <span class="lang en" style="display: none;">Qualifications</span>
                <span class="lang de" style="display: inline;">Qualifikationen</span>
                :</b> PHP, MySQL, CakePHP, Symfony3, Angular2, Bootstrap, Unit Testing, WordPress, HTML, CSS,
            JavaScript,
            jQuery, OpenStreetMap, Eclipse, Git, Github, Open Source, Continuous Integration (Travis-CI)
        </p>
        <p class="lang en" style="display: none;">Languages: German, Spanish, English</p>
        <p class="lang de" style="display: block;">Sprachen: Deutsch, Spanisch, Englisch</p>
    </div>

    <a class="header-link" href="#wrapper"><span class="lang en" style="display: none;">&lt;&lt;
            back</span><span class="lang de" style="display: inline;">&lt;&lt; zurück</span></a>
</div>

// components/pages/About.vue
<template>
    <div class="desc" id="about">

        <div>

        <img alt="Mario Rothauer" width="200" height="200" src="/img/profilbild-netidee.jpg" />

        <b>
            <span><a style="text-decoration: underline" href="https://www.foodcoopshop.com/2019/01/foodcoopshop-im-extra-blick/" target="_blank"><span style="float: none;">Bericht über FoodCoopShop im extra-blick (31.01.2019)</span></a></span>
        </b>
        <br /><br />

        <b>
            <span class="lang de">Bericht über FoodCoopShop in der Tips (14.03.2018)</span>
            <span class="lang en">Article about FoodCoopShop in Tips (in German)</span>
        </b><br />

        <p>
            <a style="text-decoration: underline" href="https://www.tips.at/news/scharnstein/wirtschaft-politik/419922-digitalisierung-unterstuetzt-die-nahversorgung-im-almtal" target="_blank"><span style="float: none;" class="lang de">Online-Version</span><span style="float: none;" class="lang en">online version</span></a>
            / <a style="text-decoration: underline" target="_blank" href="https://www.tips.at/zeitung-epaper/?ausgabe=tips-gmunden&id=31669#/22"><span style="float: none;" class="lang de">Print-Ausgabe</span><span style="float: none;" class="lang en">print version</span></a>
        </p>

        <br />

        <p class="lang en">
            <b>About me</b>:
            Mario works as a freelance web-developer since 2009. His favorite projects are open source projects with a social impact, he lives with his family in Upper Austria.
        </p>
        <p class="lang de">
            <b>Über mich</b>:
            Mario ist seit 2009 als Webentwickler selbstständig. Er arbeitet am liebsten an Open-Source-Projekten,
            die zu einer Verbesserung der Gesellschaft beitragen und lebt mit seiner Familie im Almtal / Oberösterreich.
        </p>

        <p>
            <b>
            <span class="lang en">Qualifications</span>
            <span class="lang de">Qualifikationen</span>
            :</b> Docker, CakePHP, MySQL, Unit Testing, Integration Testing, Wordpress, LeafletJS, Git, Github, Open Source, CI/CD, VSCode, HTML, CSS, JavaScript, jQuery
        </p>

        <p class="lang en"><b>Additional</b>: Several years of experience with food ordering workflow.</p>
        <p class="lang de"><b>Sonstiges</b>: Mehrjährige Erfahrung in der Online-Vorbestellung von Lebensmitteln / Erstellen von <i>stabiler</i> Software / Langfristige Wartung und Betreuung von Software-Projekten</p>

        <p class="lang en"><b>Languages</b>: German, Spanish, English</p>
        <p class="lang de"><b>Sprachen</b>: Deutsch, Spanisch, Englisch</p>

        </div>

    </div>
</template>
