// src/app/imprint/imprint.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-imprint',
    templateUrl: './imprint.component.html',
})
export class ImprintComponent implements OnInit {

    constructor() { }

    ngOnInit() {

    }

}
<div class="desc" id="imprint" style="display: none;">
    <div>
        <p>Mag. (FH) Mario Rothauer</p>
        <p>Am Birkenweg 3</p>
        <p>A-4644 Scharnstein / <span class="lang en" style="display: none;">Austria</span><span class="lang de"
                style="display: inline;">Österreich</span></p>
        <p>+43 680 217 89 39</p>
        <p><a href="mailto:office@rothauer-it.com">office@rothauer-it.com</a></p>
        <p>UID-Nr. ATU71726279</p>

        <p style="margin-top:30px;">
            <b class="lang de" style="display: inline;">Haftungsausschluss</b>
            <b class="lang en" style="display: none;">Liability of links</b>
        </p>
        <p class="lang en small" style="display: none;">
            Despite careful monitoring rothauer IT assumes no liability for the content of external links. The
            operating
            companies of the linked pages are solely responsible for their own content. If illegal websites are
            accessible via hyperlinks, please inform us so that the links could be examined and possibly
            removed.
        </p>
        <p class="lang de small" style="display: block;">
            Dieser Internetauftritt beinhaltet Links zu externen Internetauftritten Dritter, auf deren Inhalt
            der
            Medieninhaber keinen Einfluss hat. Dementsprechend kann der Medieninhaber trotz sorgfältiger Prüfung
            für
            die
            Inhalte der entsprechenden Seiten keine Verantwortung übernehmen. Für diese Inhalte ist der
            Betreiber
            der
            jeweiligen Website verantwortlich. Sollten dennoch Rechtsverletzungen in Verbindung mit einer der
            verlinkten
            Seiten erkennbar werden, wird der Link selbstverständlich umgehend entfernt.
        </p>

    </div>
    <a class="header-link" href="#wrapper"><span class="lang en" style="display: none;">&lt;&lt;
            back</span><span class="lang de" style="display: inline;">&lt;&lt; zurück</span></a>
</div>

// components/pages/Imprint.vue
<template>
    <div class="desc" id="imprint">
        <div>
        <p>Mag. (FH) Mario Rothauer<br />
            Am Birkenweg 3<br />
            A-4644 Scharnstein / <span class="lang en">Austria</span><span class="lang de">Österreich</span>
        </p>
        <p>
            <b>Büro-Adresse:</b><br />
            Grubbachstraße 14<br />
            A-4644 Scharnstein
        </p>
        <p>+43 680 217 89 39<br />
            [email]<br />
            UID-Nr. ATU71726279<br />
        </p>
        <p>
            <b>Geschäftszeiten:</b><br />
            Montag bis Mittwoch 08:30 bis 17:30 Uhr, Donnerstag 08:30 bis 12:00
        </p>
        <p style="margin-top:30px;">
            <b class="lang de">Haftungsausschluss</b>
            <b class="lang en">Liability of links</b>
        </p>
        <p class="lang en small">
            Despite careful monitoring rothauer IT assumes no liability for the content of external links. The operating companies of the linked pages are solely responsible for their own content. If illegal websites are accessible via hyperlinks, please inform us so that the links could be examined and possibly removed.
        </p>
        <p class="lang de small">
            Dieser Internetauftritt beinhaltet Links zu externen Internetauftritten Dritter, auf deren Inhalt der Medieninhaber keinen Einfluss hat. Dementsprechend kann der Medieninhaber trotz sorgfältiger Prüfung für die Inhalte der entsprechenden Seiten keine Verantwortung übernehmen. Für diese Inhalte ist der Betreiber der jeweiligen Website verantwortlich. Sollten dennoch Rechtsverletzungen in Verbindung mit einer der verlinkten Seiten erkennbar werden, wird der Link selbstverständlich umgehend entfernt.
        </p>

        </div>
    </div>
</template>
