// src/app/privacy/privacy.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-privacy',
    templateUrl: './privacy.component.html',
})
export class PrivacyComponent implements OnInit {

    constructor() { }

    ngOnInit() {

    }

}
<div class="desc" id="privacy" style="display: none;">
    <div>
        <h2>Datenschutzerklärung</h2>


        <p>Verantwortliche Stelle im Sinne der Datenschutzgesetze, insbesondere der
            EU-Datenschutzgrundverordnung
            (DSGVO), ist:</p>

        <p>Mag. (FH) Mario Rothauer<br>
            Am Birkenweg 3<br>
            A-4644 Scharnstein<br>
            E-Mail:&nbsp;<a href="mailto:office@rothauer-it.com">office@rothauer-it.com</a><br>
            Tel: +43 680 217 89 39
        </p>

        <h3>Ihre Betroffenenrechte</h3>

        <p>Unter den angegebenen Kontaktdaten unseres Datenschutzbeauftragten können Sie jederzeit folgende
            Rechte
            ausüben:</p>

        <ul>
            <li>Auskunft über Ihre bei uns gespeicherten Daten und deren Verarbeitung,</li>
            <li>Berichtigung unrichtiger personenbezogener Daten,</li>
            <li>Löschung Ihrer bei uns gespeicherten Daten,</li>
            <li>Einschränkung der Datenverarbeitung, sofern wir Ihre Daten aufgrund gesetzlicher Pflichten noch
                nicht
                löschen dürfen,</li>
            <li>Widerspruch gegen die Verarbeitung Ihrer Daten bei uns und</li>
            <li>Datenübertragbarkeit, sofern Sie in die Datenverarbeitung eingewilligt haben oder einen Vertrag
                mit
                uns
                abgeschlossen haben.</li>
        </ul>

        <p>Sofern Sie uns eine Einwilligung erteilt haben, können Sie diese jederzeit mit Wirkung für die
            Zukunft
            widerrufen.</p>

        <h3>Zwecke der Datenverarbeitung durch die verantwortliche Stelle und Dritte</h3>

        <p>Wir verarbeiten Ihre personenbezogenen Daten nur zu den in dieser Datenschutzerklärung genannten
            Zwecken.
            Eine Übermittlung Ihrer persönlichen Daten an Dritte zu anderen als den genannten Zwecken findet
            nicht
            statt. Wir geben Ihre persönlichen Daten nur an Dritte weiter, wenn:</p>

        <ul>
            <li>Sie Ihre ausdrückliche Einwilligung dazu erteilt haben,</li>
            <li>die Verarbeitung zur Abwicklung eines Vertrags mit Ihnen erforderlich ist,</li>
            <li>die Verarbeitung zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist,</li>
        </ul>

        <p>die Verarbeitung zur Wahrung berechtigter Interessen erforderlich ist und kein Grund zur Annahme
            besteht,
            dass Sie ein überwiegendes schutzwürdiges Interesse an der Nichtweitergabe Ihrer Daten haben.</p>

        <h3>Löschung bzw. Sperrung der Daten</h3>

        <p>Wir halten uns an die Grundsätze der Datenvermeidung und Datensparsamkeit. Wir speichern Ihre
            personenbezogenen Daten daher nur so lange, wie dies zur Erreichung der hier genannten Zwecke
            erforderlich
            ist oder wie es die vom Gesetzgeber vorgesehenen vielfältigen Speicherfristen vorsehen. Nach
            Fortfall
            des
            jeweiligen Zweckes bzw. Ablauf dieser Fristen werden die entsprechenden Daten routinemäßig und
            entsprechend
            den gesetzlichen Vorschriften gesperrt oder gelöscht.</p>

        <h3>Erfassung allgemeiner Informationen beim Besuch unserer Website</h3>

        <p>Wenn Sie auf unsere Website zugreifen, werden automatisch mittels eines Cookies Informationen
            allgemeiner
            Natur erfasst. Diese Informationen (Server-Logfiles) beinhalten etwa die Art des Webbrowsers, das
            verwendete
            Betriebssystem, den Domainnamen Ihres Internet-Service-Providers und ähnliches. Hierbei handelt es
            sich
            ausschließlich um Informationen, welche keine Rückschlüsse auf Ihre Person zulassen.</p>

        <p>Diese Informationen sind technisch notwendig, um von Ihnen angeforderte Inhalte von Webseiten korrekt
            auszuliefern und fallen bei Nutzung des Internets zwingend an. Sie werden insbesondere zu folgenden
            Zwecken
            verarbeitet:</p>

        <ul>
            <li>Sicherstellung eines problemlosen Verbindungsaufbaus der Website,</li>
            <li>Sicherstellung einer reibungslosen Nutzung unserer Website,</li>
            <li>Auswertung der Systemsicherheit und -stabilität sowie</li>
            <li>zu weiteren administrativen Zwecken.</li>
        </ul>

        <p>Die Verarbeitung Ihrer personenbezogenen Daten basiert auf unserem berechtigten Interesse aus den
            vorgenannten Zwecken zur Datenerhebung. Wir verwenden Ihre Daten nicht, um Rückschlüsse auf Ihre
            Person
            zu
            ziehen. Empfänger der Daten sind nur die verantwortliche Stelle und ggf. Auftragsverarbeiter.</p>

        <p>Anonyme Informationen dieser Art werden von uns ggfs. statistisch ausgewertet, um unseren
            Internetauftritt
            und die dahinterstehende Technik zu optimieren.</p>

        <h3>Cookies</h3>

        <p>Wie viele andere Webseiten verwenden wir auch so genannte „Cookies“. Cookies sind kleine Textdateien,
            die
            von einem Websiteserver auf Ihre Festplatte übertragen werden. Hierdurch erhalten wir automatisch
            bestimmte
            Daten wie z. B. IP-Adresse, verwendeter Browser, Betriebssystem und Ihre Verbindung zum Internet.
        </p>

        <p>Cookies können nicht verwendet werden, um Programme zu starten oder Viren auf einen Computer zu
            übertragen.
            Anhand der in Cookies enthaltenen Informationen können wir Ihnen die Navigation erleichtern und die
            korrekte
            Anzeige unserer Webseiten ermöglichen.</p>

        <p>In keinem Fall werden die von uns erfassten Daten an Dritte weitergegeben oder ohne Ihre Einwilligung
            eine
            Verknüpfung mit personenbezogenen Daten hergestellt.</p>

        <p>Natürlich können Sie unsere Website grundsätzlich auch ohne Cookies betrachten. Internet-Browser sind
            regelmäßig so eingestellt, dass sie Cookies akzeptieren. Im Allgemeinen können Sie die Verwendung
            von
            Cookies jederzeit über die Einstellungen Ihres Browsers deaktivieren. Bitte verwenden Sie die
            Hilfefunktionen Ihres Internetbrowsers, um zu erfahren, wie Sie diese Einstellungen ändern können.
            Bitte
            beachten Sie, dass einzelne Funktionen unserer Website möglicherweise nicht funktionieren, wenn Sie
            die
            Verwendung von Cookies deaktiviert haben.</p>

        <h3>Kontaktformular</h3>

        <p>Treten Sie bzgl. Fragen jeglicher Art per E-Mail oder Kontaktformular mit uns in Kontakt, erteilen
            Sie
            uns
            zum Zwecke der Kontaktaufnahme Ihre freiwillige Einwilligung. Hierfür ist die Angabe einer validen
            E-Mail-Adresse erforderlich. Diese dient der Zuordnung der Anfrage und der anschließenden
            Beantwortung
            derselben. Die Angabe weiterer Daten ist optional. Die von Ihnen gemachten Angaben werden zum Zwecke
            der
            Bearbeitung der Anfrage sowie für mögliche Anschlussfragen gespeichert. Nach Erledigung der von
            Ihnen
            gestellten Anfrage werden personenbezogene Daten automatisch gelöscht.</p>

        <h3>Änderung unserer Datenschutzbestimmungen</h3>

        <p>Wir behalten uns vor, diese Datenschutzerklärung anzupassen, damit sie stets den aktuellen
            rechtlichen
            Anforderungen entspricht oder um Änderungen unserer Leistungen in der Datenschutzerklärung
            umzusetzen,
            z.B.
            bei der Einführung neuer Services. Für Ihren erneuten Besuch gilt dann die neue
            Datenschutzerklärung.
        </p>

        <h3>Webanalyse mit Matomo</h3>
        <p>Unsere Website verwendet Funktionen des Webanalysedienstes Matomo. Dazu werden <b>keine</b> Cookies
            verwendet. Die dadurch erzeugten Informationen werden auf den Server des Anbieters (rothauer-it.com,
            Serverstandort: Deutschland) übertragen und dort gespeichert. Wir haben mit dem Anbieter einen
            entsprechenden Vertrag zur Auftragsdatenverarbeitung abgeschlossen.&nbsp;<b></b>Ihre IP-Adresse wird
            erfasst, aber umgehend (durch Löschung der letzten 2 Bytes) pseudonymisiert. Dadurch ist nur mehr
            eine
            grobe
            Lokalisierung möglich. Die Datenverarbeitung erfolgt auf Basis der gesetzlichen Bestimmungen des §
            96
            Abs 3
            TKG sowie des Art 6 Abs 1 lit a (Einwilligung) und/oder f (berechtigtes Interesse) der DSGVO. Unser
            Anliegen
            im Sinne der DSGVO (berechtigtes Interesse) ist die Verbesserung unseres Angebotes und unseres
            Webauftritts.
            Da uns die Privatsphäre unserer Nutzer wichtig ist, werden die Nutzerdaten pseudonymisiert. Die
            Nutzerdaten
            werden für die Dauer von 12 Monaten aufbewahrt.</p>

        <p>Sie können mittels "Opt-Out" eine Auswertung ihres Besuches verhindern:</p>
        <iframe style="border: 0; height: 100px; width: 100%;"
            src="https://www.rothauer-it.com/pwk/index.php?module=CoreAdminHome&amp;action=optOut&amp;language=de"
            width="300" height="150"></iframe>


        <p><em>Die Datenschutzerklärung wurde mit dem </em><a
                href="https://www.activemind.de/datenschutz/datenschutzhinweis-generator/" rel="noopener"
                target="_blank"><em>Datenschutzerklärungs-Generator der activeMind AG
                    erstellt</em></a><em>.</em>
        </p>

    </div>
    <a class="header-link" href="#wrapper"><span class="lang en" style="display: none;">&lt;&lt;
            back</span><span class="lang de" style="display: inline;">&lt;&lt; zurück</span></a>
</div>

// components/pages/Privacy.vue
<template>
    <div class="desc" id="privacy">
        <div>
        <h2>Datenschutzerklärung</h2>

        <p>Verantwortliche Stelle im Sinne der Datenschutzgesetze, insbesondere der EU-Datenschutzgrundverordnung (DSGVO), ist:</p>

        <p>Mag. (FH) Mario Rothauer<br />
            Am Birkenweg 3<br />
            A-4644 Scharnstein<br />
            E-Mail: <a href="mailto:office@rothauer-it.com">office@rothauer-it.com</a><br />
            Tel: +43 680 217 89 39
        </p>

        <h3>Ihre Betroffenenrechte</h3>

        <p>Unter den angegebenen Kontaktdaten unseres Datenschutzbeauftragten k&ouml;nnen Sie jederzeit folgende Rechte aus&uuml;ben:</p>

        <ul>
            <li>Auskunft &uuml;ber Ihre bei uns gespeicherten Daten und deren Verarbeitung,</li>
            <li>Berichtigung unrichtiger personenbezogener Daten,</li>
            <li>L&ouml;schung Ihrer bei uns gespeicherten Daten,</li>
            <li>Einschr&auml;nkung der Datenverarbeitung, sofern wir Ihre Daten aufgrund gesetzlicher Pflichten noch nicht l&ouml;schen d&uuml;rfen,</li>
            <li>Widerspruch gegen die Verarbeitung Ihrer Daten bei uns und</li>
            <li>Daten&uuml;bertragbarkeit, sofern Sie in die Datenverarbeitung eingewilligt haben oder einen Vertrag mit uns abgeschlossen haben.</li>
        </ul>

        <p>Sofern Sie uns eine Einwilligung erteilt haben, k&ouml;nnen Sie diese jederzeit mit Wirkung f&uuml;r die Zukunft widerrufen.</p>

        <h3>Zwecke der Datenverarbeitung durch die verantwortliche Stelle und Dritte</h3>

        <p>Wir verarbeiten Ihre personenbezogenen Daten nur zu den in dieser Datenschutzerkl&auml;rung genannten Zwecken. Eine &Uuml;bermittlung Ihrer pers&ouml;nlichen Daten an Dritte zu anderen als den genannten Zwecken findet nicht statt. Wir geben Ihre pers&ouml;nlichen Daten nur an Dritte weiter, wenn:</p>

        <ul>
            <li>Sie Ihre ausdr&uuml;ckliche Einwilligung dazu erteilt haben,</li>
            <li>die Verarbeitung zur Abwicklung eines Vertrags mit Ihnen erforderlich ist,</li>
            <li>die Verarbeitung zur Erf&uuml;llung einer rechtlichen Verpflichtung erforderlich ist,</li>
        </ul>

        <p>die Verarbeitung zur Wahrung berechtigter Interessen erforderlich ist und kein Grund zur Annahme besteht, dass Sie ein &uuml;berwiegendes schutzw&uuml;rdiges Interesse an der Nichtweitergabe Ihrer Daten haben.</p>

        <h3>L&ouml;schung bzw. Sperrung der Daten</h3>

        <p>Wir halten uns an die Grunds&auml;tze der Datenvermeidung und Datensparsamkeit. Wir speichern Ihre personenbezogenen Daten daher nur so lange, wie dies zur Erreichung der hier genannten Zwecke erforderlich ist oder wie es die vom Gesetzgeber vorgesehenen vielf&auml;ltigen Speicherfristen vorsehen. Nach Fortfall des jeweiligen Zweckes bzw. Ablauf dieser Fristen werden die entsprechenden Daten routinem&auml;&szlig;ig und entsprechend den gesetzlichen Vorschriften gesperrt oder gel&ouml;scht.</p>

        <h3>Erfassung allgemeiner Informationen beim Besuch unserer Website</h3>

        <p>Wenn Sie auf unsere Website zugreifen, werden automatisch mittels eines Cookies Informationen allgemeiner Natur erfasst. Diese Informationen (Server-Logfiles) beinhalten etwa die Art des Webbrowsers, das verwendete Betriebssystem, den Domainnamen Ihres Internet-Service-Providers und &auml;hnliches. Hierbei handelt es sich ausschlie&szlig;lich um Informationen, welche keine R&uuml;ckschl&uuml;sse auf Ihre Person zulassen.</p>

        <p>Diese Informationen sind technisch notwendig, um von Ihnen angeforderte Inhalte von Webseiten korrekt auszuliefern und fallen bei Nutzung des Internets zwingend an. Sie werden insbesondere zu folgenden Zwecken verarbeitet:</p>

        <ul>
            <li>Sicherstellung eines problemlosen Verbindungsaufbaus der Website,</li>
            <li>Sicherstellung einer reibungslosen Nutzung unserer Website,</li>
            <li>Auswertung der Systemsicherheit und -stabilit&auml;t sowie</li>
            <li>zu weiteren administrativen Zwecken.</li>
        </ul>

        <p>Die Verarbeitung Ihrer personenbezogenen Daten basiert auf unserem berechtigten Interesse aus den vorgenannten Zwecken zur Datenerhebung. Wir verwenden Ihre Daten nicht, um R&uuml;ckschl&uuml;sse auf Ihre Person zu ziehen. Empf&auml;nger der Daten sind nur die verantwortliche Stelle und ggf. Auftragsverarbeiter.</p>

        <p>Anonyme Informationen dieser Art werden von uns ggfs. statistisch ausgewertet, um unseren Internetauftritt und die dahinterstehende Technik zu optimieren.</p>

        <h3>Cookies</h3>

        <p>Wie viele andere Webseiten verwenden wir auch so genannte &bdquo;Cookies&ldquo;. Cookies sind kleine Textdateien, die von einem Websiteserver auf Ihre Festplatte &uuml;bertragen werden. Hierdurch erhalten wir automatisch bestimmte Daten wie z. B. IP-Adresse, verwendeter Browser, Betriebssystem und Ihre Verbindung zum Internet.</p>

        <p>Cookies k&ouml;nnen nicht verwendet werden, um Programme zu starten oder Viren auf einen Computer zu &uuml;bertragen. Anhand der in Cookies enthaltenen Informationen k&ouml;nnen wir Ihnen die Navigation erleichtern und die korrekte Anzeige unserer Webseiten erm&ouml;glichen.</p>

        <p>In keinem Fall werden die von uns erfassten Daten an Dritte weitergegeben oder ohne Ihre Einwilligung eine Verkn&uuml;pfung mit personenbezogenen Daten hergestellt.</p>

        <p>Nat&uuml;rlich k&ouml;nnen Sie unsere Website grunds&auml;tzlich auch ohne Cookies betrachten. Internet-Browser sind regelm&auml;&szlig;ig so eingestellt, dass sie Cookies akzeptieren. Im Allgemeinen k&ouml;nnen Sie die Verwendung von Cookies jederzeit &uuml;ber die Einstellungen Ihres Browsers deaktivieren. Bitte verwenden Sie die Hilfefunktionen Ihres Internetbrowsers, um zu erfahren, wie Sie diese Einstellungen &auml;ndern k&ouml;nnen. Bitte beachten Sie, dass einzelne Funktionen unserer Website m&ouml;glicherweise nicht funktionieren, wenn Sie die Verwendung von Cookies deaktiviert haben.</p>

        <h3>Kontaktformular</h3>

        <p>Treten Sie bzgl. Fragen jeglicher Art per E-Mail oder Kontaktformular mit uns in Kontakt, erteilen Sie uns zum Zwecke der Kontaktaufnahme Ihre freiwillige Einwilligung. Hierf&uuml;r ist die Angabe einer validen E-Mail-Adresse erforderlich. Diese dient der Zuordnung der Anfrage und der anschlie&szlig;enden Beantwortung derselben. Die Angabe weiterer Daten ist optional. Die von Ihnen gemachten Angaben werden zum Zwecke der Bearbeitung der Anfrage sowie f&uuml;r m&ouml;gliche Anschlussfragen gespeichert. Nach Erledigung der von Ihnen gestellten Anfrage werden personenbezogene Daten automatisch gel&ouml;scht.</p>

        <h3>&Auml;nderung unserer Datenschutzbestimmungen</h3>

        <p>Wir behalten uns vor, diese Datenschutzerkl&auml;rung anzupassen, damit sie stets den aktuellen rechtlichen Anforderungen entspricht oder um &Auml;nderungen unserer Leistungen in der Datenschutzerkl&auml;rung umzusetzen, z.B. bei der Einf&uuml;hrung neuer Services. F&uuml;r Ihren erneuten Besuch gilt dann die neue Datenschutzerkl&auml;rung.</p>

        <p><em>Die Datenschutzerkl&auml;rung wurde mit dem </em><a href="https://www.activemind.de/datenschutz/datenschutzhinweis-generator/" rel="noopener" target="_blank"><em>Datenschutzerkl&auml;rungs-Generator der activeMind AG erstellt</em></a><em>.</em></p>

        </div>
    </div>
</template>
